image: python:3.10

before_script:
  - id
  - pwd
  - apt update && apt install -y nodejs npm

stages:
  - build
  - deploy

build:app:
  stage: build
  script:
    - if [ ! -e venv/bin/activate ] ; then python3 -m venv venv; fi
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python3 generate.py
    - npm install bower
  artifacts:
    paths:
      - web/

deploy:prod:
  stage: deploy
  dependencies:
    - build:app
  environment:
    name: production
    url: https://learn.atilla.org
  only:
    - master
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRODUCTION_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan -H webstatic-prod.prod.infra.atilla.org >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - rsync --checksum --recursive --delete --delete-during --itemize-changes --verbose web/ learn@webstatic-prod.prod.infra.atilla.org:/srv/vhosts/learn/website
