type: training
title: Formation Tekiens.net 2024
date: 16/10/2024
image: training-tekiens.jpg
short: Formation Tekiens.net 2024
peertube_id :
  - c852bf56-5041-4dc7-98b9-092b5c7805ab
authors:
  - grandellou
  - frickkevin
description: Présentation de tekiens.net et de ses fonctionnalités. Détails pour rejoindre et aider au développement du projet.